import { app, BrowserWindow, IpcMain, ipcMain, shell, webContents, dialog } from "electron";
import { AppCommandMap, AppEventDetail, BasePlugin, PluginContext } from "floating-live";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { serializeError } from "serialize-error";
import { is } from "@electron-toolkit/utils";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

const __dirname = path.dirname(fileURLToPath(import.meta.url));

declare module "floating-live" {
  interface AppCommandMap {
    devtools: () => void;
    "electronGui.showOpenDialog": (options: Electron.OpenDialogOptions) => Promise<Electron.OpenDialogReturnValue>;
    [name: `${string}.snapshot`]: () => any;
  }
}

interface FLEGWebContents extends Electron.WebContents {
  send(channel: "event", eventName: string, detail: AppEventDetail<any>): void;
}

interface FLEGIpcMain extends IpcMain {
  handle(
    channel: "command",
    listener: (
      e: Electron.IpcMainInvokeEvent,
      command: string,
      ...args: any[]
    ) => Promise<[boolean, any]>
  ): void;
  handle(
    channel: "connect",
    listener: (e: Electron.IpcMainInvokeEvent, connectOptions: { snapshots: string[] }) => [boolean]
  ): void;
}

export default class ElectronGui extends BasePlugin {
  static pluginName = "electronGui";
  mainWindow: BrowserWindow | null = null;
  readonly app: Electron.App = app;

  init(ctx: PluginContext) {
    // init app

    app.whenReady().then(() => {
      // Set app user model id for windows
      // electronApp.setAppUserModelId("com.electron");

      this.createMainWindow();
    });

    app.on("window-all-closed", () => {
      if (process.platform !== "darwin") {
        app.quit();
      }
    });

    app.on("activate", () => {
      if (BrowserWindow.getAllWindows().length === 0) {
        this.createMainWindow();
      }
    });

    // init ipcMain

    // 处理连接，连接成功后返回快照信息
    (ipcMain as FLEGIpcMain).handle("connect", (e, { snapshots }: { snapshots: string[] }) => {
      const allSnapshots: Record<string, any> = {};
      snapshots.forEach((name) => {
        try {
          allSnapshots[name] = ctx.call(`${name}.snapshot`);
        } catch (e) { }
      });
      e.sender.send("snapshot", allSnapshots);
      // console.log(allSnapshots)
      return [true];
    });

    // 处理指令
    (ipcMain as FLEGIpcMain).handle(
      "command",
      async <T extends keyof AppCommandMap>(
        e: Electron.IpcMainInvokeEvent,
        command: string,
        ...args: any[]
      ) => {
        try {
          const result = await ctx.call<T>(command as T, ...(args as Parameters<AppCommandMap[T]>));
          return [true, result];
        } catch (err) {
          console.error(serializeError(err));
          return [false, serializeError(err)];
        }
      }
    );

    // 发送事件
    ctx.on("event", (event) => {
      webContents.getAllWebContents().forEach((e: FLEGWebContents) => {
        e.send("event", event.name, event.detail);
        // console.log("event", event.name, event.detail)
      });
    });

    this.ctx.registerCommand("devtools", () => {
      this.mainWindow?.webContents.openDevTools();
    });
    this.ctx.registerCommand("electronGui.showOpenDialog", async (commandContext, options) => {
      const result = await dialog.showOpenDialog(this.mainWindow!, options);
      return result;
    });
  }
  createMainWindow() {
    if (this.mainWindow) return;
    const mainWindow = new BrowserWindow({
      height: 600,
      width: 800,
      titleBarStyle: "hidden",
      titleBarOverlay: {
        color: "#FFFFFF00",
      },
      webPreferences: {
        preload: path.join(__dirname, "../preload/index.mjs"),
        webSecurity: false,
        sandbox: false,
      },
    });

    mainWindow.on("ready-to-show", () => {
      mainWindow.show();
    });

    mainWindow.webContents.setWindowOpenHandler((details) => {
      shell.openExternal(details.url);
      return { action: "deny" };
    });

    // HMR for renderer base on electron-vite cli.
    // Load the remote URL for development or the local html file for production.
    if (is.dev && process.env["ELECTRON_RENDERER_URL"]) {
      mainWindow.loadURL(process.env["ELECTRON_RENDERER_URL"]);
    } else {
      mainWindow.loadFile(path.join(__dirname, "../renderer/index.html"));
    }

    mainWindow.on("close", () => {
      this.mainWindow = null;
    });
    this.mainWindow = mainWindow;
  }
}
